server:
  port: 8080
spring:
  application:
    name: timesheet_rest
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
application:
  logging:
    enabled: true
    level: warn
    print-args: false
  recover:
    enabled: true
    level: warn
    log-exception: true
  timer:
    enabled: true
    level: warn